### ISSUE TITLE
Question about pre-trained embedding setting

### ISSUE THREAD

**Issue by Jasper-Wu** [JinheonBaek/GEN#3]
Hi, 

thanks for your great work first!

I have a question about the pre-trained embedding generated with Distmult. Do we need to ignore "unseen entities" when we pre-train, i.e., remove all the triples which contain unseen entities? Or we just put the whole KG into the pre-training process, and then mask them in inductive/transductive training?

Thanks!

**Comment by JinheonBaek** [comment]
Hi,

Thank you for your interest in our work.

When we pre-train the embedding of seen entities with DistMult,
we totally ignore unseen entities, in other words, remove all triplets which contain unseen entities.

Best regards,
Jinheon Baek
