### ISSUE TITLE
About Training Gmatching MetaR and FSRL

### ISSUE THREAD

**Issue by ZifengDing** [JinheonBaek/GEN#4]
Hi,

I am wondering how you train these methods in your task. As I understand, these three methods use entity pair matching and they do not use embeddings of sparse relations during training and evaluation. Do you also neglect the triple relations (relations in the triples containing unseen entities) while training them?

And also I think Gmatching, MetaR and FSRL are originally using meta-learning framework. What is the difference between, e.g., Gmatching and Gmatching*?

**Comment by JinheonBaek** [comment]
Hi,

Thank you for your interest.

The training datasets are the same across all models. Thus, if the triple relations containing unseen entities appear in the training dataset, then we use them for training.

Gmatching denotes the model trained under the meta-learning of relations, whereas, Gmatching* denotes the model trained under the meta-learning of entities that we propose.

**Comment by JinheonBaek** [comment]
Hi there; if there are any further questions, please feel free to reopen this issue. Thanks.
